# Generated by Django 5.2.8 on 2025-11-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(help_text='Write a description about status', max_length=256),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
